language: haskell
ghc: 7.8
branches:
  only:
    - source
env:
  global:
    - secure: "fkytTKJVcJZUW5OTYcKW5D3/hQTwgqfKkguA0nbpqan+1q4amyovAxJLxBPgIn/snyNZV1b7jgwN3TExRUjE0mf0O0tqo9/X5Yg/t+HfpwN2aCDVEmd+7z1jea8GliVNesiamvZfFeaaYzzlNu0zkdf9o0nkHETKY2d/j++jM6Q="
install:
  - cabal sandbox init
  - cabal configure --disable-library-profiling --disable-tests --disable-library-coverage --disable-benchmarks --disable-split-objs
  - cabal install -j --disable-documentation hakyll
script:
  - make build
  - git config --global user.name "Î»-Wolf bot"
  - git config --global user.email info@functionalvilnius.lt
  - ' [ "${TRAVIS_PULL_REQUEST}" = "true" ] || make commit upload 2>&1 | sed -r "s|https://(.*)@|https://{{SECRET}}@|g" '
