language: haskell
ghc: 7.8
branches:
  only:
    - source
env:
  global:
    - secure: "fkytTKJVcJZUW5OTYcKW5D3/hQTwgqfKkguA0nbpqan+1q4amyovAxJLxBPgIn/snyNZV1b7jgwN3TExRUjE0mf0O0tqo9/X5Yg/t+HfpwN2aCDVEmd+7z1jea8GliVNesiamvZfFeaaYzzlNu0zkdf9o0nkHETKY2d/j++jM6Q="
install:
  - curl https://github.com/functional-vilnius/functional-vilnius.github.io/releases/download/cabal-sandbox/cabal-sandbox.tar.gz | tar xf
script:
  - make build
  - git config --global user.name "Î»-Wolf bot"
  - git config --global user.email info@functionalvilnius.lt
  - ' [ "${TRAVIS_PULL_REQUEST}" = "true" ] || make commit upload 2>&1 | sed -r "s|https://(.*)@|https://{{SECRET}}@|g" '

#before_deploy:
#  - tar cf cabal-sandbox.tar.gz .cabal-sandbox/ cabal.sandbox.config
#deploy:
#  provider: releases
#  api_key:
#      secure: "Cf3npZ4C9Vseog2IUAapL5HF7oV4QvWOD19cOyWmUJqwqD5Ejl0LyIoQUx/j2/PMCxAyZKYy7NM6N79UmHmB/+Sl/boQ5YrJ5xwDmaEcAdc5tc0Rca4OOpSXsYSY8fMSqMIZZ+sujkbebtXN6vj40wKbA4E5D6FeKUQFI3/pzxI="
#  skip_cleanup: true
#  file: cabal-sandbox.tar.gz
#  on:
#      tags: false
#      all_branches: true
#      branch: source
