language: haskell
ghc: 7.8
branches:
  only:
    - cabal-sandbox-builds
env:
  global:
    - secure: "fkytTKJVcJZUW5OTYcKW5D3/hQTwgqfKkguA0nbpqan+1q4amyovAxJLxBPgIn/snyNZV1b7jgwN3TExRUjE0mf0O0tqo9/X5Yg/t+HfpwN2aCDVEmd+7z1jea8GliVNesiamvZfFeaaYzzlNu0zkdf9o0nkHETKY2d/j++jM6Q="
    - CABAL_FLAGS="-j --disable-documentation --disable-tests --reorder-goals
        --disable-library-profiling --disable-library-coverage --enable-library-vanilla
        --disable-library-for-ghci --disable-benchmarks --enable-split-objs
        --enable-shared"
install:
  - cabal sandbox init
  - cabal install $CABAL_FLAGS -fhttps pandoc
  - cabal install $CABAL_FLAGS
script:
  - make build

before_deploy:
  - XZ_OPT="-9" tar caf cabal-sandbox.tar.lzma .cabal-sandbox/ cabal.sandbox.config
deploy:
  provider: releases
  api_key:
      secure: "Cf3npZ4C9Vseog2IUAapL5HF7oV4QvWOD19cOyWmUJqwqD5Ejl0LyIoQUx/j2/PMCxAyZKYy7NM6N79UmHmB/+Sl/boQ5YrJ5xwDmaEcAdc5tc0Rca4OOpSXsYSY8fMSqMIZZ+sujkbebtXN6vj40wKbA4E5D6FeKUQFI3/pzxI="
  skip_cleanup: true
  file: cabal-sandbox.tar.lzma
  on:
      tags: false
      all_branches: true
      branch: source
